### ISSUE TITLE
Issue with power extension

### ISSUE THREAD

**Issue by glentress** [Pitmairen/bryton-offline#1]
Hi, first of all, let me say a big thank you for putting this neat program together. It is so much better than the online version and saves a lot of time. I am not familiar with code so I'm afraid you'll have to bear with me in my explanation of the problem as I don't really know the correct terminology for things.

When I download a TCX file using the program, and then try and upload it to a third part program (ie. WKO+, golden cheetah) it seems that the power data is not picked up. I had a look at the tcx file in notepad and it seems the power data is specified under "extensions". For example:

< Extensions >
              < a:TPX >
                < a:Speed >11.25< /a:Speed >
                < a:Watts >195< /a:Watts >
              < /a:TPX >
< /Extensions >"

When I compared this to the file I get from the online program, I noticed that the "a" is replaced by "ns3". Like this:

"< Extensions >
              < ns3:TPX >
                < ns3:Speed >11.25< /ns3:Speed >
                < ns3:Watts >195< /ns3:Watts >
              < /ns3:TPX >
< /Extensions >"

Going through the file and replacing all "a" with "ns3" seemed to fix the problem and I was able to get my power data to be picked up by third party programs.

Also, I don't think my power data is being uploaded to Strava when using the bryton offline program directly. Maybe this has something to do with the above problem?

Thanks and keep up the good work.

Liam

**Comment by Pitmairen** [comment]
Unless i have completely misunderstood the concept of XML, this is bugs in the other software. They are probably hardcoded to search for "ns3", but wheter the prefix is "ns3" or "a" or something else shouldn't matter if the xml parsing is done correctly.

It's easy to fix though, all that is needed is to change the following line to use 'ns3' instead of 'a':
https://github.com/Pitmairen/bryton-offline/blob/master/tcx.py#L45

As i said this isn't a bug with my sofware, so it shouldn't really be necessary to change this, but it seems like a lot of software have problem with this so i will do it.

By the way, i'm just wondering if you are using linux or have access to a computer running linux?
I'm looking for someone with a powermeter for my other project:
https://github.com/Pitmairen/bryton-gps-linux

**Comment by Pitmairen** [comment]
This should be fixed now.
